id: ICE8165A4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T13:25:06+00:00'
last_modified: '2022-06-09T08:30:01.608266+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ8010
  title: སེར་སྨད་ཟུར་བཀོལ་སྤྱི་མཐའ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    96C8:
      image_group_id: I1PD96582
      title: Volume 1 of ser smad zur bkol spyi mtha'
      total_pages: 636
      order: 1
      base_file: 96C8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
